window.LinkedOut = window.LinkedOut || {};

LinkedOut.FIELD_ALIASES = {
  first_name: ["first name", "fname", "given name", "your first name", "legal first name", "first"],
  last_name: ["last name", "lname", "surname", "family name", "your last name", "legal last name", "last"],
  email: ["email", "e-mail", "email address", "your email", "contact email", "work email", "personal email"],
  phone: ["phone", "telephone", "tel", "cell", "cellphone", "mobile", "phone number", "mobile number", "contact number", "mobile phone"],
  address: ["address", "street address", "street", "address line 1", "address line", "home address", "mailing address"],
  city: ["city", "town"],
  state: ["state", "province", "state/province", "region"],
  zip: ["zip", "zip code", "postal code", "zipcode", "zip/postal code", "postcode"],
  country: ["country", "country/region", "nation"],
  work_authorization: ["work authorization", "authorized to work", "legally authorized", "work eligibility", "are you authorized", "employment eligibility", "authorized"],
  visa_sponsorship: ["visa sponsorship", "sponsorship", "require sponsorship", "need sponsorship", "will you now or in the future require sponsorship", "immigration sponsorship"],
  salary_expectation: ["salary", "salary expectation", "expected salary", "desired salary", "compensation", "desired compensation", "salary requirements"],
  years_experience: ["years of experience", "years experience", "total experience", "experience", "how many years"],
  start_date: ["start date", "available start date", "availability", "earliest start date", "when can you start", "date available"],
  current_company: ["current company", "current employer", "present employer", "most recent employer"],
  current_title: ["current title", "current job title", "current position", "present title"],
  highest_degree: ["degree", "highest degree", "education level", "highest education", "level of education"],
  school: ["school", "university", "college", "institution", "school name", "university name"],
  major: ["major", "field of study", "area of study", "concentration", "discipline"],
  graduation_year: ["graduation year", "grad year", "year of graduation", "expected graduation", "graduation date"],
  gpa: ["gpa", "grade point average", "cumulative gpa"],
  linkedin_url: ["linkedin", "linkedin url", "linkedin profile", "linkedin link"],
  github_url: ["github", "github url", "github profile", "github link"],
  portfolio_url: ["portfolio", "portfolio url", "portfolio link", "portfolio website"],
  personal_website: ["website", "personal website", "personal site", "web site", "homepage", "blog"],
  gender: ["gender", "gender identity", "what is your gender"],
  race_ethnicity: ["race", "ethnicity", "race/ethnicity", "racial background", "ethnic background", "race ethnicity"],
  veteran_status: ["veteran", "veteran status", "military", "protected veteran", "are you a veteran"],
  disability_status: ["disability", "disability status", "disabled", "do you have a disability"],
  resume: ["resume", "cv", "curriculum vitae", "upload resume", "add resume", "attach resume", "resume/cv", "upload cv"],
};
